### ISSUE TITLE
cargo-outdated unconditionally tries to look for master branch for git deps

### ISSUE THREAD

**Issue by crumblingstatue** [kbknapp/cargo-outdated#266]
If you add a git dependency that has the main branch as `main` instead of `master`, cargo-outdated will fail:
`cannot locate remote-tracking branch 'origin/master'; class=Reference (4); code=NotFound (-3)`

**Comment by msrd0** [comment]
I encountered a different error message when using a git dependency with an alternative default branch:

```
thread 'main' panicked at 'Cannot find matched versions of package time from source https://github.com/time-rs/time?branch=main', /home/msrd0/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-outdated-0.9.10/src/cargo_ops/temp_project.rs:377:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /build/rust/src/rustc-1.43.1-src/vendor/backtrace/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /build/rust/src/rustc-1.43.1-src/vendor/backtrace/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:332
  13: cargo_outdated::cargo_ops::temp_project::TempProject::find_update::{{closure}}
  14: cargo_outdated::cargo_ops::temp_project::TempProject::find_update
  15: cargo_outdated::cargo_ops::temp_project::TempProject::update_version_and_feature
  16: cargo_outdated::cargo_ops::temp_project::TempProject::write_manifest_semver
  17: cargo_outdated::execute
  18: cargo_outdated::main
  19: std::rt::lang_start::{{closure}}
  20: main
  21: __libc_start_main
  22: _start
```

Note that using current rust nightly (1.54), the `branch` does not need to be specified anymore when using the default branch, even if that branch is not called `master`.

**Comment by deg4uss3r** [comment]
I have a branch that updates us to `cargo` `0.54.0` which resolves this. I just need to test it more 

https://github.com/kbknapp/cargo-outdated/tree/degausser/bump_cargo_0.54 😃
