### ISSUE TITLE
Index ouf of bounds

### ISSUE THREAD

**Issue by fpoli** [kbknapp/cargo-outdated#286]
I found that `cargo outdated` panics when running on our project.

Project: https://github.com/viperproject/prusti-dev, commit `5705580`.

Command:
```
 RUST_BACKTRACE=1 cargo outdated --root-deps-only --workspace
```
Output:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/fpoli/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-outdated-0.9.17/src/cargo_ops/temp_project.rs:409:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1e9319d93aea755c444c8f8ff863b0936d7a4b6/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/e1e9319d93aea755c444c8f8ff863b0936d7a4b6/library/core/src/panicking.rs:100:14
   2: core::panicking::panic_bounds_check
             at /rustc/e1e9319d93aea755c444c8f8ff863b0936d7a4b6/library/core/src/panicking.rs:76:5
   3: core::option::Option<T>::unwrap_or_else
   4: cargo_outdated::cargo_ops::temp_project::TempProject::find_update
   5: cargo_outdated::cargo_ops::temp_project::TempProject::update_version_and_feature
   6: cargo_outdated::cargo_ops::temp_project::TempProject::write_manifest_latest
   7: cargo_outdated::execute
   8: cargo_outdated::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Version: `cargo-outdated v0.9.17`

**Comment by kbknapp** [comment]
Going to close this as stale. Sorry for letting this hang. If it's still an issue this far into the future please feel free to re-open and ping me.

**Comment by DragonDev1906** [comment]
@kbknapp This bug still exists (from what I can tell it's the same issue - I cannot re-open the issue):
Version: 0.15.0
Repository: https://github.com/fortanix/rust-sgx Commit: `b6f0262`
Command: `RUST_BACKTRACE=1 cargo outdated`

```
thread 'main' panicked at /home/jens/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-outdated-0.15.0/src/cargo_ops/temp_project.rs:446:33:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: cargo_outdated::cargo_ops::temp_project::TempProject::find_update
   4: cargo_outdated::cargo_ops::temp_project::TempProject::update_version_and_feature
   5: cargo_outdated::cargo_ops::temp_project::TempProject::write_manifest_latest
   6: cargo_outdated::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
