### ISSUE TITLE
Crashes with "package cache lock is not currently held"

### ISSUE THREAD

**Issue by figsoda** [kbknapp/cargo-outdated#291]
```
$ RUST_BACKTRACE=1 cargo outdated
thread 'main' panicked at 'package cache lock is not currently held, Cargo forgot to call `acquire_package_cache_lock` before we got to this stack frame', /build/cargo
-outdated-0.10.0-vendor.tar.gz/cargo/src/cargo/util/config/mod.rs:1542:9
stack backtrace:
   0: std::panicking::begin_panic
   1: cargo::util::config::Config::assert_package_cache_locked
   2: lazycell::LazyCell<T>::try_borrow_with
   3: <cargo::sources::registry::remote::RemoteRegistry as cargo::sources::registry::RegistryData>::prepare
   4: cargo::sources::registry::index::RegistryIndex::summaries
   5: cargo::sources::registry::index::RegistryIndex::query_inner_with_online
   6: <cargo::sources::registry::RegistrySource as cargo::core::source::Source>::query
   7: cargo::core::source::Source::query_vec
   8: cargo_outdated::cargo_ops::temp_project::TempProject::find_update
   9: cargo_outdated::cargo_ops::temp_project::TempProject::update_version_and_feature
  10: cargo_outdated::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mattico** [comment]
I'm getting this error with v0.10.0 but not v0.9.18, strangely enough.

**Comment by figsoda** [comment]
me too, since master is 0.10.0 right now I omitted the version

**Comment by ckaran** [comment]
Same for me, just adding more datum points in case it'll help.

```bash
$ RUST_BACKTRACE=full cargo outdated -vvvvvv
  Parsing... current workspace
Resolving... current workspace
  Parsing... compat workspace
thread 'main' panicked at 'package cache lock is not currently held, Cargo forgot to call `acquire_package_cache_lock` before we got to this stack frame', /home/cfkaran2/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.57.0/src/cargo/util/config/mod.rs:1542:9
stack backtrace:
   0:     0x556cad1ee46a - std::backtrace_rs::backtrace::libunwind::trace::h3fea1eb2e0ba2ac9
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x556cad1ee46a - std::backtrace_rs::backtrace::trace_unsynchronized::h849d83492cbc0d59
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x556cad1ee46a - std::sys_common::backtrace::_print_fmt::he3179d37290f23d3
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x556cad1ee46a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h140f6925cad14324
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x556cad0faeac - core::fmt::write::h31b9cd1bedd7ea38
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5:     0x556cad1edbf4 - std::io::Write::write_fmt::h1fdf66f83f70913e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6:     0x556cad1eda33 - std::sys_common::backtrace::_print::he7ac492cd19c3189
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x556cad1eda33 - std::sys_common::backtrace::print::hba20f8920229d8e8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x556cad1eda33 - std::panicking::default_hook::{{closure}}::h714d63979ae18678
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9:     0x556cad1eda33 - std::panicking::default_hook::hf1afb64e69563ca8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10:     0x556cad1eda33 - std::panicking::rust_panic_with_hook::h02231a501e274a13
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
  11:     0x556cad0558d4 - std::panicking::begin_panic::{{closure}}::hb5b0321191d1abc7
  12:     0x556cad0558a6 - std::sys_common::backtrace::__rust_end_short_backtrace::ha9a793d1a10ad7dc
  13:     0x556cace45b96 - std::panicking::begin_panic::hca48052704ff1f66
  14:     0x556cacffccd7 - cargo::util::config::Config::assert_package_cache_locked::h4816c02da16093e7
  15:     0x556cacee03ba - lazycell::LazyCell<T>::try_borrow_with::h6b3b2934277946ca
  16:     0x556cacffcc21 - <cargo::sources::registry::remote::RemoteRegistry as cargo::sources::registry::RegistryData>::prepare::hd3bc341bec877714
  17:     0x556cacee3aa0 - cargo::sources::registry::index::RegistryIndex::summaries::h531c91d2938e61e0
  18:     0x556cacee8ab3 - cargo::sources::registry::index::RegistryIndex::query_inner_with_online::hae2682ee88fa4744
  19:     0x556cacf94d71 - <cargo::sources::registry::RegistrySource as cargo::core::source::Source>::query::h16146fb1fed4cff5
  20:     0x556cacf94b89 - cargo::core::source::Source::query_vec::h59b2b7506245adb7
  21:     0x556cad0d9060 - cargo_outdated::cargo_ops::temp_project::TempProject::find_update::h77b8226e50f438fb
  22:     0x556cad0d7196 - cargo_outdated::cargo_ops::temp_project::TempProject::update_version_and_feature::h29dafbc06d42096c
  23:     0x556cad0e7908 - cargo_outdated::main::h11760cdfcf48adea
  24:     0x556cad0bd653 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7ad0af2c0a601ab9
  25:     0x556cad0e11bd - main
  26:     0x7f6f28b6a0b3 - __libc_start_main
                               at /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
  27:     0x556cace5863e - _start
  28:                0x0 - <unknown>
```

## Meta

```bash
$ cargo outdated -Vv
cargo-outdated v0.10.0

lsb_release -a:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

uname -a:
Linux Hammer 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

rustc -vV:
rustc 1.56.1 (59eed8a2a 2021-11-01)
binary: rustc
commit-hash: 59eed8a2aac0230a8b53e89d4e99d55912ba6b35
commit-date: 2021-11-01
host: x86_64-unknown-linux-gnu
release: 1.56.1
LLVM version: 13.0.0

cargo -vV:
cargo 1.56.0 (4ed5d137b 2021-10-04)
release: 1.56.0
commit-hash: 4ed5d137baff5eccf1bae5a7b2ae4b57efad4a7d
commit-date: 2021-10-04

rustc +beta -vV:
rustc 1.57.0-beta.3 (708d57e28 2021-11-01)
binary: rustc
commit-hash: 708d57e288d051a6238ed56039ffeac158e10e84
commit-date: 2021-11-01
host: x86_64-unknown-linux-gnu
release: 1.57.0-beta.3
LLVM version: 13.0.0

cargo +beta -vV:
cargo 1.57.0-beta (b2e52d7ca 2021-10-21)
release: 1.57.0
commit-hash: b2e52d7cab0a286ee9fcc0c17510b1e72fcb53eb
commit-date: 2021-10-21
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1-DEV (sys:0.4.49+curl-7.79.1 vendored ssl:OpenSSL/1.1.1l)
os: Ubuntu 20.04 (focal) [64-bit]

rustc +nightly -vV:
rustc 1.58.0-nightly (8b09ba6a5 2021-11-09)
binary: rustc
commit-hash: 8b09ba6a5d5c644fe0f1c27c7f9c80b334241707
commit-date: 2021-11-09
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0

cargo +nightly -vV:
cargo 1.58.0-nightly (2e2a16e98 2021-11-08)
release: 1.58.0
commit-hash: 2e2a16e983f597da62bc132eb191bc3276d4b1bb
commit-date: 2021-11-08
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.79.1-DEV (sys:0.4.50+curl-7.79.1 vendored ssl:OpenSSL/1.1.1l)
os: Ubuntu 20.04 (focal) [64-bit]
```

**Comment by cfvescovo** [comment]
I am experiencing the same issue

**Comment by cfvescovo** [comment]
```
RUST_BACKTRACE=full cargo outdated -vvvvvv
  Parsing... current workspace
Resolving... current workspace
  Parsing... compat workspace
 Updating... compat workspace
    Updating crates.io index
Resolving... compat workspace
  Parsing... latest workspace
thread 'main' panicked at 'package cache lock is not currently held, Cargo forgot to call `acquire_package_cache_lock` before we got to this stack frame', /Users/cfv/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.57.0/src/cargo/util/config/mod.rs:1542:9
stack backtrace:
   0:        0x10dfb8aff - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf1ee81583766da09
   1:        0x10dec431b - core::fmt::write::h8dc218a6eb2426a8
   2:        0x10dfb83ea - std::io::Write::write_fmt::heef3e26d448f8c80
   3:        0x10dfb81fe - std::panicking::rust_panic_with_hook::ha5146542f697c8af
   4:        0x10de1d355 - std::panicking::begin_panic::{{closure}}::h264228ef6431bd2c
   5:        0x10de1d329 - std::sys_common::backtrace::__rust_end_short_backtrace::h5d3ff7c3a427b5fd
   6:        0x10e1502f9 - std::panicking::begin_panic::hb529eeed6d29525e
   7:        0x10ddc380e - cargo::util::config::Config::assert_package_cache_locked::hcb19988e51b2f7e2
   8:        0x10dca16ae - lazycell::LazyCell<T>::try_borrow_with::h69bc5a9cc7abbe37
   9:        0x10ddc3749 - <cargo::sources::registry::remote::RemoteRegistry as cargo::sources::registry::RegistryData>::prepare::hed6fd989633de9ff
  10:        0x10dca486b - cargo::sources::registry::index::RegistryIndex::summaries::h700e605af01844f3
  11:        0x10dca9a1f - cargo::sources::registry::index::RegistryIndex::query_inner_with_online::h1a7f1a96dec5ab60
  12:        0x10dd5c215 - <cargo::sources::registry::RegistrySource as cargo::core::source::Source>::query::h54860084e67bcaba
  13:        0x10dd5c020 - cargo::core::source::Source::query_vec::h74db05e2723a921a
  14:        0x10dea1c9a - cargo_outdated::cargo_ops::temp_project::TempProject::find_update::h485de6ea9de48878
  15:        0x10de9fc6e - cargo_outdated::cargo_ops::temp_project::TempProject::update_version_and_feature::h6b322c260983f4f4
  16:        0x10deb1db5 - cargo_outdated::main::h9acaa87d6ab2f370
  17:        0x10de865b6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h92ddba8739670594
  18:        0x10dea9f26 - _main

```

**Comment by fredrik-jansson-se** [comment]
I as well, please let me know if I can provide any details to help figuring this out!

**Comment by yatesco** [comment]
Same

**Comment by mattico** [comment]
I'm also getting the crash when running `cargo-outdated` on the `cargo-outdated` crate, which is edition `2018`, so I don't think that matters.

I ran a git-bisect to determine the cause of the issue. For those of you who (like me) haven't used bisect before, it's actually pretty easy:
```
git bisect start
git bisect bad
git bisect good 5682a1aed68075fcccdc787d5fe9941c2ab0ff74
git bisect run cargo run -- outdated
```
The first bad commit is 2a5bf77f4a76134b37d5bc279428e8ec5530f8b1. Seems pretty benign, but I'm guessing from the error message that `acquire_package_cache_lock` is required before using `SourceConfigMap`.

**Comment by bikeshedder** [comment]
For anyone looking for an easy fix. Just downgrade to version `0.9.18` which doesn't contain this bug:
```shell
cargo install --version 0.9.18 cargo-outdated
```

**Comment by oconnor663** [comment]
Installing from the git repo also fixed this for me. Here's the command from the README:

```
cargo install --locked --git https://github.com/kbknapp/cargo-outdated
```

We might want to reopen this issue until the fix is shipped to crates.io? I didn't find it on my first pass after I encountered this bug.

**Comment by ckaran** [comment]
For what it's worth, 0.10.1 seems to have fixed the issues for me.
